### ISSUE TITLE
Many errors in 1.8

### ISSUE THREAD

**Issue by GoogleSites** [snowgears/shopbugs#17] opened 2018-12-25 21:30 UTC
When using Shop v. 1.8.0.1, it will not load as it requires PLAYER_HEAD to be present in the GuiConfig.yml.
PLAYER_HEAD is only for 1.13+ and I can't set it to anything else or it will throw this error:  https://pastebin.com/SBiLcN1A

When I have it set to PLAYER_HEAD, it will (obviously) not recognize the enum: https://pastebin.com/JHdU7mS4

Thanks in advance :)

**Comment by LuckyClutch07** [comment] 2018-12-30 04:33
PLEASE FIX THIS ISSUE !!! I CAN'T USE THIS PLUGIN!!! IS NOT FUNCTIONAL AS IT CLAIMS TO BE 1.7.x - 1.13.x

**Comment by snowgears** [comment] 2019-01-01 05:39
For any minecraft version 1.13 or lower, you will need to use a shop version lower than shop 1.8. This is a duplicate of issue #11

**Closed** 2019-01-01 05:40 UTC
Labels: duplicate
