### ISSUE TITLE
offline player shop sales notifcation

### ISSUE THREAD

**Issue by PotatoIQ** [snowgears/shopbugs#182] opened 2020-11-30 15:56 UTC
**Is your feature request related to a problem? Please describe.**
If player is offline and join in the server, they don't get notified of their sales while they were gone.

**Describe the solution you'd like**
If any of the player shops made sales/buys while they were offline, then once they login, a message would show in chat with total sales they made, can be a negative sales if ppl sold items to that player.

**Comment by snowgears** [comment] 2020-11-30 19:39
Duplicate of #175 and planned with #30

**Closed by snowgears** 2020-11-30 19:39 UTC
Labels: enhancement
