### ISSUE TITLE
Bug gui menu

### ISSUE THREAD

**Issue by istarengwa** [snowgears/shopbugs#225] opened 2021-06-19 10:18 UTC
**Describe the bug**

Hello, when a player clicks on the gui menu of the / shop it generates a lot of lag on the inventory click event (gui) just for a player who clicks, the server time goes from 20 to 15, so when 20 players click at the same time time, the server crashed.

I have plenty of other plugin which uses gui with teleportation and which does not generate lag.

So I deactivated it to the regret of the players, if it could be patched it could make a lot of people happy!

**Version:**
 - Spigot version: purpurclip-1169 (paper 1.16.5)
 - Shop version: 1.8.2.6

**Comment by snowgears** [comment] 2021-06-20 16:48
Duplicate of #96

**Closed by snowgears** 2021-06-20 16:48 UTC
Labels: bug
