### ISSUE TITLE
Rounding error with partial buys

### ISSUE THREAD

**Issue by ZepsiZola** [snowgears/shopbugs#382] opened 2023-01-04 22:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: 1.19.3
- Shop Version: 1.8.4.1
```

### Server startup log

https://paste.gg/p/anonymous/be5fc035d3354c2d80052e2219d1dad6

### Shop config files

https://gist.github.com/ZepsiZola/0da7824a843609a9e520283a0ef722d1

### Error log (if applicable)

No Error Log

### Bug description

It's basically explained in this discord message.

![image](https://user-images.githubusercontent.com/49735083/210659945-cae9220a-87fb-4022-bc0a-3d81524d1598.png)

### Steps to reproduce

1. Create a shop that sells 128 sand for 1 diamond
2. Put only 64 sand in the chest
3. Have at least 1 diamond in your inventory
4. Buy sand from ShopChest
5. It gives you 64 sand and takes your diamond
6. There is no more sand in the chest

### Expected behaviour

It should tell you that there is not enough stock in the chest to buy the sand.

### Actual behaviour

1. Create a shop that sells 128 sand for 1 diamond
2. Put only 64 sand in the chest
3. Have at least 1 diamond in your inventory
4. Buy sand from ShopChest
5. It gives you 64 sand and takes your diamond
6. There is no more sand in the chest

**Comment by snowgears** [comment] 2023-01-21 22:09
Duplicate of #380

**Closed by snowgears** 2023-01-21 22:09 UTC
Labels: bug
