### ISSUE TITLE
Signs not applying to chest appropriately.

### ISSUE THREAD

**Issue by SenpaiRyan** [snowgears/shopbugs#33] opened 2019-01-26 23:58 UTC
**Describe the bug**
Whenever I start a shop the signs orientation does not face that of which the chest is facing. Seems I can only make a shop when I am facing true south or east.

**To Reproduce**
1. I face North & West
2. Attempt to create a shop.
3. Sign creates sideways or facing away with shop. Causing entity to fall to ground.
4. Am not able to fix in config.

**Expected behavior**
I expected the signs to go in all 4 directions and apply to the chest when I am done.

**Screenshots**
![](https://i.imgur.com/XoIx2bt.png)

![](https://i.imgur.com/DFzUFgq.png)

![](https://i.imgur.com/EbRsit9.png)

![](https://i.imgur.com/Edqs3HO.png)

**Version:**
Paper 1.13.2 latest fork
Latest version of shop  1.8.0.1

**Comment by snowgears** [comment] 2019-02-01 18:54
Can you please try to reproduce this bug with default spigot instead of paper spigot? Shop does not officially support paper spigot and I want to make sure this is not a bug with paper spigot. Thanks!

**Comment by mov51** [comment] 2019-02-22 03:34
can confirm this is happening on what appears to be a default spigot server. 
![image](https://user-images.githubusercontent.com/16448318/53218124-e9c36800-3628-11e9-9c82-7c8a34cc6363.png)

**Comment by BillyGalbreath** [comment] 2019-07-23 21:01
Fixed in next release

**Closed by BillyGalbreath** 2019-07-23 21:01 UTC
Labels: bug, question
