### ISSUE TITLE
Combo shop have their sell price squared

### ISSUE THREAD

**Issue by markusew** [snowgears/shopbugs#167] opened 2020-10-28 11:35 UTC
**Describe the bug**
Whenever someone tries to create a combo shop the sell price they listed is squared making it near impossible to conveniently create combo shops.

**To Reproduce**
Make a combo shop and it should be apparent

**Version:**
 - Spigot version: tuinity 1.16.3
 - Shop version: 1.8.2.2

**Comment by snowgears** [comment] 2020-10-29 18:56
Duplicate of #143

**Closed by snowgears** 2020-10-29 18:56 UTC
Labels: bug
