### ISSUE TITLE
Add tax (global and maybe per item)

### ISSUE THREAD

**Issue by ElTodoFull** [snowgears/shopbugs#348] opened 2022-10-28 03:43 UTC
**Is your feature request related to a problem? Please describe.**
Inflation. Money is always increasing, as well as resources.

**Describe the solution you'd like**
Adding a tax when:
In "buy" (the owner sells) shops, the client/buyer pays the shown price, but the seller receives money after tax.
In "sell" (the owner buys) shops, the sign automatically corrects the price after tax so the client/seller receives the shown money.

And to battle resource inflation, if possible, configure a tax per item, for example dirt has 3%, and netherite ingots have 50% economy tax.

**Describe alternatives you've considered**
It could be possible to make this with the api on buy event, but I'm not sure if the selling mechanics would do well with that.

**Additional context**
Free plugin ChestShop has that option, but doesn't have an option per item, but does have price limits per item. (But I still prefer tax as to not tamper too much with the market.)

**Comment by snowgears** [comment] 2022-11-09 02:21
Duplicate of #150

**Closed by snowgears** 2022-11-09 02:21 UTC
Labels: enhancement
