### ISSUE TITLE
[BUG] Cannot type

### ISSUE THREAD

**Issue by NotLifeGD** [snowgears/shopbugs#444] opened 2024-09-06 17:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: 1.19.4
- Shop Version: 1.9.0.1
```

### Server startup log

No such file

### Shop config files

https://paste.gg/p/anonymous/a2f87af9445e4388b35570483de1977b

### Error log (if applicable)

https://paste.gg/p/anonymous/6df66cae928b4735aad6252e9a25531b

### Bug description

Whenever a player tries to create a shop, they get put in creative, then when they exit out or something it does not let them chat anymore.

### Steps to reproduce

1. Start creating a shop
2. Randomly get put in creative by shop

### Expected behaviour

Not get put in creative and be able to chat

### Actual behaviour

Cannot chat

**Comment by OstlerDev** [comment] 2024-09-08 21:28
Duplicate of #422 

Bug has been fixed in upcoming release 1.9.1.0!

**Closed by OstlerDev** 2024-09-08 21:28 UTC
Labels: bug
