### ISSUE TITLE
digits after the decimal point for this price

### ISSUE THREAD

**Issue by K4rfunkelchen** [snowgears/shopbugs#43] opened 2019-02-20 21:04 UTC
Hey first of all I say thank you for the good plugin but do I have 1-2 criticism or improvement suggestions first can you put anywhere the Gamble Items? The other thing is rather a suggestion that you could buy and sell like in ChestShop with a sign. you can't have any digits after the decimal point for this price

**Comment by Plumzie** [comment] 2019-02-21 11:22
The decimal thing is a duplicate of #1

**Comment by K4rfunkelchen** [comment] 2019-02-21 11:47
> The decimal thing is a duplicate of #1

Yes and the bug is known since 17 Dec 2018 and has not been fixed yet.

**Comment by Plumzie** [comment] 2019-02-21 13:28
> 
> Yes and the bug is known since 17 Dec 2018 and has not been fixed yet.

That doesn't mean you should just make another issue for it. Anyway the dev is extremely inactive in terms of updates for the plugin. The last update was on the 4th of December.

**Closed** 2019-02-21 18:57 UTC
Labels: duplicate, enhancement
