### ISSUE TITLE
Adding user as a shop manager

### ISSUE THREAD

**Issue by DJIronic** [snowgears/shopbugs#209] opened 2021-03-16 20:36 UTC
**Is your feature request related to a problem? Please describe.**
Our players are not happy with being able to add their friends to their shops as co-owners or managers, so they can withdraw the items or fill up the store to stock.

**Describe the solution you'd like**
Just a command to add a player (UUID) to the users shop.

**Describe alternatives you've considered**
No idea about any other options.

**Additional context**
Just the idea of option for players to add / remove users to access their shop, they can have all permissons, but not the one for breaking the shop. Or maybe even that.

It can be on two levels: 
Manager - cannot remove the shop
Co-owner - can remove and replace the shop

**Comment by snowgears** [comment] 2021-03-21 22:20
Duplicate of #139

**Closed** 2021-03-21 22:21 UTC
Labels: enhancement
