### ISSUE TITLE
Towny Advanced Support

### ISSUE THREAD

**Issue by srnyx** [snowgears/shopbugs#102] opened 2020-07-21 21:35 UTC
**Describe the solution you'd like**
I want there to be support for the Towny Advanced plugin where it limits the creation of shops to Towny shop plots.

**Describe alternatives you've considered**
ChestShop plugin

**Comment by snowgears** [comment] 2021-01-01 20:34
Duplicate of #75

**Closed by snowgears** 2021-01-01 20:34 UTC
Labels: enhancement
