### ISSUE TITLE
Update on the sign rotation issue

### ISSUE THREAD

**Issue by CrunchyChicken** [snowgears/shopbugs#40] opened 2019-02-08 21:17 UTC
The latest version of SHOP
Spigot 1.13.1

recreate by placing chest then trying to make a shop.

![2019-02-08_13 19 34](https://user-images.githubusercontent.com/47410308/52506704-35dfc880-2ba4-11e9-9094-c7eb45f97cc8.png)
![2019-02-08_13 19 29](https://user-images.githubusercontent.com/47410308/52506705-35dfc880-2ba4-11e9-8da9-d311293a94cc.png)
![2019-02-08_13 19 28](https://user-images.githubusercontent.com/47410308/52506706-35dfc880-2ba4-11e9-8343-05798e8129dd.png)
![2019-02-08_13 19 26](https://user-images.githubusercontent.com/47410308/52506707-35dfc880-2ba4-11e9-8f55-05a8dd1a5a56.png)
![2019-02-08_13 19 25](https://user-images.githubusercontent.com/47410308/52506708-36785f00-2ba4-11e9-91d0-da39bb6f47d9.png)

**Comment by snowgears** [comment] 2019-02-11 18:45
This is a duplicate of issue #33

**Closed by snowgears** 2019-02-11 18:45 UTC
