### ISSUE TITLE
Shops placed by a new plot owner keep reverting to the old shop on restart.

### ISSUE THREAD

**Issue by cfi2017** [snowgears/shopbugs#53] opened 2019-05-20 13:29 UTC
**Describe the bug**
We've had an instant where a player was banned for cheating and their market plot was sold to  another player. That player then created new shops at the location of the old ones.

Two of these shop signs keep reverting to the old owners signs. This seems to occur on restarts.

**To Reproduce**
I can't accurately reproduce the issue. If you want to contact me on discord, message @Raptor#0001.

**Version:**
 - Spigot version: Paper Spigot 1.13.2
 - Shop version 1.8.0.1

**Comment by BillyGalbreath** [comment] 2019-08-17 19:41
I figured out the cause of this. I'm working out a plan to fix it.

Basically, the Shop plugin stores data in the format of `PlayerName (UUID).yml` and when a player changes their mojang account name they get a 2nd data file created. A duplicate, but with a different name. When that person breaks their shop it only gets removed from the data file with their new/current name. When someone else makes a shop at that same location, depending on which file loads first, the old player's data from their old username will override it.

I'm seeing similar issues with enderchests when a user changes their name and shop enderchests are enabled.

**Comment by SiuanSong** [comment] 2019-10-05 19:48
Thanks Billy!!  I've been having to delete double data files for ages now.  I reported it many moons ago, though I don't know where that report/post was.  Perhaps simply storing data by UUID alone.  Though I don't know how 'simple' that is.
I'm glad it's going to be worked on.
Thank you!

**Comment by PhanaticD** [comment] 2019-10-08 01:19
this has been a problem for years :(

**Comment by SiuanSong** [comment] 2020-02-22 17:19
Any update on this?

**Comment by snowgears** [comment] 2020-08-19 22:36
Fixed in 1.8.2. Please reopen if this persists.

**Closed by snowgears** 2020-08-19 22:36 UTC
Labels: bug
