### ISSUE TITLE
My item Names not showing up to !

### ISSUE THREAD

**Issue by WaffleV2** [snowgears/shopbugs#10] opened 2018-12-19 20:13 UTC
Like this 
![image](https://user-images.githubusercontent.com/46007477/50245444-0e227e80-0405-11e9-800d-6fffb637a9cb.png)
and this 
![image](https://user-images.githubusercontent.com/46007477/50245478-285c5c80-0405-11e9-9867-16961004cfa8.png)

**Comment by snowgears** [comment] 2018-12-22 21:40
Duplicate of issue #4

**Closed by snowgears** 2018-12-22 21:40 UTC
Labels: duplicate
