### ISSUE TITLE
Laggspike while opening a shop

### ISSUE THREAD

**Issue by martijnpu** [snowgears/shopbugs#97] opened 2020-05-26 07:24 UTC
**Describe the bug**
Server freeses sometimes when someone opens a chest, kicking all online players

**Screenshots**
https://pastebin.com/ZypU2k8B

**Version:**
 - Spigot version: Latest Paper
 - Shop version 1.8.1

**Comment by tWizT3ddreaMr** [comment] 2020-06-28 04:14
Opens a chest or opens the gui? The log you provided only shows gui classes.

**Comment by martijnpu** [comment] 2020-06-28 11:27
That's right. I mean /shop. Where you can see all shops in the server.

Op zo 28 jun. 2020 06:14 schreef tWizT3ddreaMr <notifications@github.com>:

**Comment by snowgears** [comment] 2020-08-20 03:22
Duplicate of #96

**Closed by snowgears** 2020-08-20 03:22 UTC
Labels: bug
