### ISSUE TITLE
[BUG] Block above shop chest deleted on Paper 1.17.1 (doesn't occur on 1.16.5)

### ISSUE THREAD

**Issue by MacTh3Mac** [snowgears/shopbugs#256] opened 2021-09-12 12:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: PaperSpigot 1.17.1
- Shop Version: 1.8.29
```

### Server startup log

No Errors in Log

### Shop config files

https://gist.github.com/MacTh3Mac/6214bfb9b9bbcb65e48b769f565342ff

### Bug description

When making a shop with a block above the check blocking it the following occurs:

None set at item type. (deletes block above)
Item set as item type and space blocked (deleted block above)

Identical config on Paper 1.16.5 this error / issue is not present.  It is specific to 1.17.1

This issue occurs irrespective of what block is blocking the shop chest.

### Steps to reproduce

https://www.youtube.com/watch?v=5YZksRWrNH8

### Expected behaviour

Not to delete the block, and give error if blocked / or if option in config enabled to convert to a "none" item display type.

### Actual behaviour

Deletes the block above shop chest (1.17.1 only)

### Other information

https://www.youtube.com/watch?v=5YZksRWrNH8

**Comment by MacTh3Mac** [comment] 2021-09-13 10:06
Reply from Author:   Posting here to help others until next updates fixes.

> This is an error with the light block. Please set ‘displayLightLevel’ to 0 until this is fixed.
#3181SnowGears, Yesterday at 11:59 PM

**Comment by snowgears** [comment] 2021-09-14 16:02
Duplicate of #249

**Closed by snowgears** 2021-09-14 16:02 UTC
Labels: bug
