### ISSUE TITLE
[BUG] Swift sneak doen't show up correctly

### ISSUE THREAD

**Issue by Plattio** [snowgears/shopbugs#336] opened 2022-08-08 21:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: Paper 1.19 #61
- Shop Version: 1.8.3.7
```

### Server startup log

not necessary

### Shop config files

not necessary

### Error log (if applicable)

not necessary

### Bug description

If i create a Shop with Swift Sneak and leftclick the ChestShop, it is shown as Unknown 2 instead of Swift Sneak 2.
![image](https://user-images.githubusercontent.com/65920067/183520373-6be1881d-4e1e-416f-a73c-9cca6e6532b7.png)

### Steps to reproduce

If i create a Shop with Swift Sneak and leftclick the ChestShop for prview, it is shown as Unknown 2 instead of Swift Sneak 2.

### Expected behaviour

Swift Sneak 2 

### Actual behaviour

Unknown 2

**Comment by snowgears** [comment] 2022-08-12 17:45
Duplicate of #330

**Closed by snowgears** 2022-08-12 17:45 UTC
Labels: bug
