### ISSUE TITLE
Shift buy/sell admin shops

### ISSUE THREAD

**Issue by Rawxdealz** [snowgears/shopbugs#195] opened 2021-01-25 20:48 UTC
Is it possible to make chests where people can buy or sell 1 item, but if they hold shift (or an other button) they can buy/sell everything they have or can affort. Or 64 instead of 1?

Got a question also: in the gamble shop: for what is the 1st number?

Great plugin

**Comment by snowgears** [comment] 2021-01-26 22:09
The first number is not used for gamble shops as it gives a random item.

As for the "buy stack" idea that is suggested in this ticket and is a duplicate of #159 

Thank you! I'm glad you like it!

**Closed by snowgears** 2021-01-26 22:09 UTC
Labels: enhancement
