### ISSUE TITLE
Item Names not showing up

### ISSUE THREAD

**Issue by xXJustXx** [snowgears/shopbugs#4] opened 2018-12-17 20:49 UTC
First of all, your Shop plugin is really amazing. But there are a few things which could be improved. It looks like item names aren't working corretly in 1.13.2 yet:

https://imgur.com/ezM3Hox

It just shows an empty field there. And the second thing is my suggestion. Could you please add support for React's (https://www.spigotmc.org/resources/21057/) 
Culling/Puring of entities? I mean that the shop things don't get removed... And for CMI (https://www.spigotmc.org/resources/3742/) too please.

And I got an error using your plugin with Confiscate (https://www.spigotmc.org/resources/37893/) 
https://pastebin.com/9NdAucNa.
I don't know if it's an error in your plugin or in Confiscate. Anyways I contaced the author of it already and I'm waiting for a response

**Comment by snowgears** [comment] 2018-12-18 05:39
As for your feature request, I have reached out to the developer of react to add support, both CMI and Confiscate are not currently planned but welcome to work with the developers if they reach out to me.

**Comment by EHAndrew** [comment] 2019-01-13 01:41
I am having the same problem. If it's a basic item, not renamed, it's showing up as [ ] with the default config. There needs to be a way to use [item] and [item type] interchangeably. Maybe default to [item type], but switch to [item] if the item is renamed from its default material.

**Comment by hamcoremusic** [comment] 2019-01-25 04:11
I can also confirm that item names are not showing up in 1.13.2!

**Comment by arizrain1** [comment] 2019-01-25 17:47
Can I please ask the status of this bug fix?  I have 2 servers in 1.13.2 that have the same issue with no name, if no display is chosen.

**Comment by SiuanSong** [comment] 2019-02-15 09:28
Seconding a small status update please. :) Even if it's "haven't gotten there yet."

**Comment by snowgears** [comment] 2019-02-19 01:28
haven't gotten there yet ;)

**Comment by SiuanSong** [comment] 2019-02-19 01:34
lol thank you!

**Comment by Plumzie** [comment] 2019-02-21 13:36
I check spigot and here everyday to see if this is fixed haha

**Comment by thunderlight411** [comment] 2019-02-24 09:48
Is there any ATE when this is going to be fixed ?

**Comment by hamcoremusic** [comment] 2019-05-10 12:47
I hope this gets fixed on a 1.14 update! I love this plugin!!

**Comment by kittygaming99** [comment] 2019-08-16 06:35
I would love an update on this!

**Comment by BillyGalbreath** [comment] 2019-08-16 18:44
If you use the 1.14 update with Paper server then the item names will be correct. If you use Spigot or CraftBukkit then a best-guess is used based on limited availability of that information server side. Paper is highly recommended.

**Closed by BillyGalbreath** 2019-08-16 18:44 UTC
Labels: bug

**Comment by kittygaming99** [comment] 2019-08-16 23:26
I have tested that and it seems to work perfectly on 1.14.4 paper. I have a survival server on 1.13.2 which can not be updated to the new version however. I would still say this is a bug and if I could at least be told where to start looking if I wanted to fix it myself then that would be great. I understand @BillyGalbreath that you think this bug is caused by a lack of information availability server side. Is there any API or something similar I could use to give myself more options, excluding updating to 1.14?

**Comment by BillyGalbreath** [comment] 2019-08-16 23:46
If you use Paper API you can get proper item names using this method

https://papermc.io/javadocs/paper/1.13/org/bukkit/inventory/ItemFactory.html#getI18NDisplayName-org.bukkit.inventory.ItemStack-

Sorry, I can't further. Life is too busy for backporting fixes to legacy software. Ain't nobody got time for that ;)
