### ISSUE TITLE
[BUG] world black list reverts to example after reloading shop or restarting the server

### ISSUE THREAD

**Issue by RUINCRAFT** [snowgears/shopbugs#257] opened 2021-09-13 00:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Other unexpected behaviour

### Environment

```markdown
- Server Version: paper spigot
- Shop Version: 1.8.2.9
```

### Server startup log

https://paste.gg/p/anonymous/de20c9ea3fdd438e866d58a0f6403272

### Shop config files

https://paste.gg/p/anonymous/6549fa086e90493fa97af3964673916a

### Bug description

when changing 
# Add the names of worlds that you do not want shops to be able to be created in here #
worldBlacklist:
  example_world: true
  example2_world: true

to 

# Add the names of worlds that you do not want shops to be able to be created in here #
worldBlacklist:
  world_nether: true
  world_the_end: true

i can /shop reload or restart the server and it reverts back to the example worlds

### Steps to reproduce

when changing 
# Add the names of worlds that you do not want shops to be able to be created in here #
worldBlacklist:
  example_world: true
  example2_world: true

to 

# Add the names of worlds that you do not want shops to be able to be created in here #
worldBlacklist:
  world_nether: true
  world_the_end: true

i can /shop reload or restart the server and it reverts back to the example worlds

### Expected behaviour

should be to let me blacklist shops in worlds

### Actual behaviour

keeps the default setting

**Comment by RUINCRAFT** [comment] 2021-09-13 00:51
im sorry its paper spigot 1.17.1

**Comment by snowgears** [comment] 2021-09-14 16:01
Duplicate of #239

**Closed by snowgears** 2021-09-14 16:01 UTC
Labels: bug
