### ISSUE TITLE
Doublechest not getting properly registered

### ISSUE THREAD

**Issue by DJIronic** [snowgears/shopbugs#207] opened 2021-03-13 20:17 UTC
**Describe the bug**
Something like 50% of doublechests are not bein registered and simply report "our of stock" even when there is an item in the chest.

When I come as an admin and click it, it will change to glass covered item (even if glass is disabled in the list) and shop will register, but not on all times (shulkers did not work even when the item put in the chest was the one used for selecting the shop item).

On the other side, books or sugasr canes registered the doublechat without a problem

**To Reproduce**
Create a doublechest shop and try to sell elytra or shulker or whatever (even exactly the same you click on the sign)

**Expected behavior**
Just doublechest store.

**Screenshots**

![image](https://user-images.githubusercontent.com/9658012/111043091-ffd73780-8440-11eb-80c4-a4c2e6f9ca64.png)

**Version:**
 - Spigot version: 1.16.5
 - Shop version: latest

**Comment by Dragonber1** [comment] 2021-03-14 13:20
This is related to [#192](https://github.com/snowgears/shopbugs/issues/192#issue-788624729), basically shops wont work if the sign is placed anywhere except the front of a chest, so double chest shops only work if the sign is placed in the front. In my testing this bug was only present for chests and enderchests, barrels and shulkers work correctly.

**Comment by snowgears** [comment] 2021-03-21 22:19
Duplicate of #192 . Will be fixed in next update.

**Closed by snowgears** 2021-03-21 22:19 UTC
Labels: bug
