### ISSUE TITLE
[BUG] Shop Signs not working 1.20.X

### ISSUE THREAD

**Issue by Ste3et** [snowgears/shopbugs#405] opened 2023-06-20 16:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: Paper 1.20.1 #43
- Shop Version: 1.8.4.4
```

### Server startup log

https://paste.gg/p/anonymous/ecd36b9eeeeb4737be326ab91a8bcb90

### Shop config files

https://gist.github.com/Ste3et/191625be643330e891606ba24e951ca5

### Bug description

On my TestServer **1.20.1** the shop Sign didn't work, you can rightclick the sign without any kind of Feedback.
These unormal behaivior is present on old placed Shops aswell on new buildet Shops.
The Creation of Shops works great but the buy & sell interaction won't work.

Sorry for the report.

### Steps to reproduce

1. Place a Chest
2. Place a Sign
3. Create a Shop sign
4. On another Player you should try to buy or sell from/to shop

### Expected behaviour

You should buy or sell Items to/from shops via Sign Rightclick

### Actual behaviour

Players can't use Shop signs

**Comment by snowgears** [comment] 2023-06-20 19:02
Duplicate of #403 .

Its an issue with paper/purpur. Updating to the latest stable version of your server software should fix it

**Closed by snowgears** 2023-06-20 19:02 UTC
Labels: bug

**Comment by Ste3et** [comment] 2023-06-20 19:53
Nice try to Help me but Paper 1.20.1 #43 IS the latest Version of 1.20.1?
https://papermc.io/downloads/paper
https://github.com/PaperMC/paper/commit/3756f5bbf566fde4aa619bf8d4215f68567621d3
