### ISSUE TITLE
[BUG] Shop holograms don't support HEX/RGB colour codes

### ISSUE THREAD

**Issue by iLemon** [snowgears/shopbugs#398] opened 2023-05-17 19:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Compatibility issue

### Environment

```markdown
- Server Version: 1.19.3
- Shop Version: 1.8.4.3
```

### Server startup log

Will send privately

### Shop config files

Default (have not touched config)

### Error log (if applicable)

n/a

### Bug description

![image](https://github.com/snowgears/shopbugs/assets/18317307/c93e02ee-4dfb-4442-ab3f-02b7587699ae)
![image](https://github.com/snowgears/shopbugs/assets/18317307/34f60a67-9032-4f4b-ac66-ebacc13ae402)
![image](https://github.com/snowgears/shopbugs/assets/18317307/1c19cb51-6220-4657-9360-2e013c76edc4)

### Steps to reproduce

1. Create item with RGB colour codes in the name.
2. Creat a shop with them

### Expected behaviour

The proper item name colour should display. It works fine in the chat messages so the support for it is already there.

### Actual behaviour

The holograms revert to using legacy colour codes.

**Comment by snowgears** [comment] 2023-06-30 19:51
Duplicate of #360

**Closed by snowgears** 2023-06-30 19:51 UTC
Labels: bug
