### ISSUE TITLE
Shops not working when created on the right, left and back sides of chests

### ISSUE THREAD

**Issue by Dragonber1** [snowgears/shopbugs#208] opened 2021-03-14 14:45 UTC
**Describe the bug**
This is a an in depth explanation of the problem shown in #207 and #192.

Shops don't work correctly when placing the sign on the left, right and back sides of a chest, trapped chest or ender chest.

The shops created this way won't detect the stock in chests instantly and won't have player and block protection, so anyone can access the chest and blocks can be placed on top of the item display, causing it to bug out and throw console errors: https://pastebin.com/QJCBDJ9Y

**To Reproduce**
1. Place a sign on the left side, right side or back side of a chest, trapped chest or ender chest.
2. Create any type of shop
3. Create shop by clicking the sign with any item
4. Try to shift click chest = See error
5. Other player click chest= See error
6. Place blocks on top of the item display = See error

**Expected behavior**
Shops should work when placing the sign on any side of a chest.

**Screenshots**

https://user-images.githubusercontent.com/65039705/111072522-319cdc80-84db-11eb-8a27-10d1b1acd501.mp4

**Version:**
 - Paper version 1.16.5 build 467
 - Shop version 1.8.2.4
 - EssentialsX version 2.19.0 build 96
 - Vault version 1.7.3

**Comment by snowgears** [comment] 2021-03-21 22:19
Duplicate of #192 . Will be fixed in next update.

**Closed by snowgears** 2021-03-21 22:19 UTC
Labels: bug
