### ISSUE TITLE
Buy stack on click + shift

### ISSUE THREAD

**Issue by Tractorzysta** [snowgears/shopbugs#298] opened 2022-01-24 07:52 UTC
Like in other chest shop plugins we should be able to buy in stacks anyway. Lot of people are creating shops with 1 item on click because it's easier to choose prize. But other customers don't like this shops. "Hmmm, let's buy double chest of chicken, give me 10 min."
In my opinion shift+R/L klick should be good option to buy in stacks (or everything if want to make it more customizable in config) in all shops.

**Comment by snowgears** [comment] 2022-01-24 17:24
Duplicate of #159

**Closed by snowgears** 2022-01-24 17:24 UTC
Labels: enhancement
