### ISSUE TITLE
Players can just open Chests?

### ISSUE THREAD

**Issue by DeadlyRadi0** [snowgears/shopbugs#170] opened 2020-11-04 05:04 UTC
When i creat a shop, other players can just take Items right out of the chest. I dont know how to fix this "bug".

Version:
 - Spigot version: [Spigot 1.16.3]
 - Shop version: [1.8.2.2]

**Comment by snowgears** [comment] 2020-11-04 05:23
Can you try with no other plugins installed? You may have another plugin overriding this.

**Comment by DeadlyRadi0** [comment] 2020-11-04 14:36
I am using a Plugin called BlockLocker, but i fixed it.
I reinstalled BlockLocker, and than it worked.
But i found another bug:
When you place a double chest under a glas block, players can certinly open the chest again.
![Uploading 2020-11-04_15.32.55.png…]()

**Comment by snowgears** [comment] 2020-11-04 17:52
Again, this is almost certainly caused by another plugin overriding the behavior. Please test this without other plugins installed to confirm.

**Comment by snowgears** [comment] 2020-11-09 23:51
Closing this. Please reopen again if this issue persists after testing without other plugins overriding.

**Closed by snowgears** 2020-11-09 23:51 UTC
Labels: bug
