### ISSUE TITLE
Chests separate from signs

### ISSUE THREAD

**Issue by Segysmundo** [snowgears/shopbugs#41] opened 2019-02-10 17:13 UTC
Have you thought about the idea of being able to link chests and signs without them being connected?
Similar to how the plugin SignShop does it.

Basically players would be able to place a sign somewhere in the shop, but keep the chests with the items in their house so they don't take up space in their shop. They would have to click on the chest and then on the sign to link them or the other way around.

Similar to how it's done now but this time they would have to click once more since the chest and sign wouldn't be together.

**Comment by snowgears** [comment] 2019-02-11 18:47
Duplicate of issue #39

**Closed by snowgears** 2019-02-11 18:47 UTC
Labels: enhancement
