### ISSUE TITLE
[BUG] playerInteractEvent error

### ISSUE THREAD

**Issue by Fowleyy** [snowgears/shopbugs#306] opened 2022-03-22 16:50 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: Purpur 1.18.2
- Shop Version: 1.8.3.5
```

### Server startup log

https://paste.gg/p/anonymous/5d5ee71490b54f4f8db9d833afb5e7ff

### Shop config files

https://paste.gg/p/anonymous/a37a4ea13e2a40a1bebbb506bab1bc4b

### Error log (if applicable)

https://paste.gg/p/anonymous/788d54a8e4e447adb3ff084a00b598e7

### Bug description

If I click sign in any type of shop, its throw this error.

### Steps to reproduce

Just try any interaction with any shop

### Expected behaviour

 just mess in console

### Actual behaviour

 just mess in console

**Comment by snowgears** [comment] 2022-04-21 20:29
Fixed in 1.8.3.6 (in progress)

**Closed by snowgears** 2022-04-21 20:29 UTC
Labels: bug

**Comment by snowgears** [comment] 2022-04-22 00:06
Duplicate of #304
