### ISSUE TITLE
[Feature Request] Support for land claiming plugins (Specifically Towny, or Lands)

### ISSUE THREAD

**Issue by AZFire1** [snowgears/shopbugs#154] opened 2020-10-05 22:32 UTC
**Is your feature request related to a problem? Please describe.**
My feature request is not related to any problems. I thought it would be nice if there was a feature which would allow support for (Lands/Towny) so you are restricted to making shops in Towns/Lands. There also could be support added for other protection plugins as well in the future.

**Describe the solution you'd like**
As I said, this isn't a problem, it's just a feature I'd like to see being added sometime in the future. There are other chestshop plugins that have support for Lands & Towny such as QuickShop and I think it would be nice to have in Shop as well.

**Describe alternatives you've considered**
Not worrying about this feature.

**Additional context**
None.

**Comment by snowgears** [comment] 2020-10-05 23:59
Duplicate of #102

**Closed by snowgears** 2020-10-05 23:59 UTC
Labels: enhancement
