### ISSUE TITLE
ConcurrentModificationException when reloading the plugin through GUI

### ISSUE THREAD

**Issue by Shnatta** [snowgears/shopbugs#246] opened 2021-08-17 12:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Error in console

### Environment

```markdown
- Server Version: 1.16.5 AirPlane git-Airplane-10
- Shop Version: 1.8.2.9
```

### Server startup log

Not relevant

### Shop config files

Not relevant as both are default

### Error log (if applicable)

https://paste.gg/p/anonymous/cf5d2cd89bc74222a75b24765bc52326

### Bug description

When typing /chestshop and going into the "Commands" category for operators and then clicking on the bone (Refresh Shop Displays), the plugin throws a ConcurrentModificationException.

### Steps to reproduce

Explained in Bug description

### Expected behaviour

The plugin should successfully refresh shop displays

### Actual behaviour

The plugin throws a ConcurrentModificationException as described in Bug description

### Other information

None needed

**Comment by snowgears** [comment] 2021-09-14 20:37
Duplicate of #240

**Closed by snowgears** 2021-09-14 20:37 UTC
Labels: bug
