### ISSUE TITLE
[BUG] Logging fails due to a long item name

### ISSUE THREAD

**Issue by jeeukko** [snowgears/shopbugs#457] opened 2024-10-30 12:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Data loss, Error in console

### Environment

```markdown
- Server Version: Paper 1.21.1
- Shop Version: 1.9.0.1
```

### Server startup log

-

### Shop config files

-

### Error log (if applicable)

https://paste.gg/p/anonymous/e585991bce7049808adefcf757f0574d

### Bug description

Logging fails due to a long item name. For example SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE does not fit shop_transaction tables item field which is CHAR(32). I changed it manually to CHAR(255) and it works

### Steps to reproduce

1. Set up logging
2. Make a shop with SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE (or any other item with name more than 32 characters)
3. Use the shop

### Expected behaviour

It should log the transaction

### Actual behaviour

Error in console and no logentry

**Comment by OstlerDev** [comment] 2024-12-10 01:02
Duplicate of #466

**Closed as completed by OstlerDev** 2024-12-10 01:02 UTC
Labels: bug
