### ISSUE TITLE
Shop signs do not face the correct direction

### ISSUE THREAD

**Issue by CrunchyChicken** [snowgears/shopbugs#38] opened 2019-02-07 06:03 UTC
**Describe the bug**
https://pastebin.com/1DFWeU0R

**To Reproduce**
i placed a sign and it didnt make a shop so i did /shop reload and thus the paste bin

**Expected behavior**
Make a shop and reload plugin

**Screenshots**
N/a

**Version:**
 - Spigot 1.13.2
 - Shop version whatever is on the download > https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/

**Additional context**
plz msg my discord so i know what im doing wrong if you can DumbLilChicken#9678

**Comment by snowgears** [comment] 2019-02-07 15:35
Please remove all the config files from the shop folder and restart the server to allow new ones to generate. Please let me know if this does not fix your issue.

**Comment by CrunchyChicken** [comment] 2019-02-07 19:05
I can make shops now but for some reason they rotate to face N/S and not on the chest

![2019-02-07_11 04 16](https://user-images.githubusercontent.com/47410308/52436104-3b67e080-2ac8-11e9-9448-3c45dd5b7298.png)
![2019-02-07_11 03 28](https://user-images.githubusercontent.com/47410308/52436105-3b67e080-2ac8-11e9-8a0e-94bcc81e9f11.png)

**Comment by snowgears** [comment] 2019-02-07 19:20
This is odd indeed. I will look into this!

**Comment by snowgears** [comment] 2019-02-07 19:21
Duplicate of issue #33

**Closed by snowgears** 2019-02-07 19:21 UTC
Labels: bug

**Comment by CrunchyChicken** [comment] 2019-02-08 01:53
how do i fix the issue since I'm not using paper?? I'm using regular spigot?

**Comment by snowgears** [comment] 2019-02-08 20:48
I incorrectly assumed the issue was with paper spigot but it in fact seems to be something deeper. So I changed the title to reflect the bug

**Comment by CrunchyChicken** [comment] 2019-02-11 04:34
i need the plugin to work so what are my options?

**Comment by snowgears** [comment] 2019-02-11 18:48
I am working on a fix. In the meantime, downgrading to Minecraft 1.12 and a shop version under 1.8 will fix this but I will work on a fix for 1.13

**Comment by CrunchyChicken** [comment] 2019-02-13 08:02
i really appreciate it, sadly i can't go to 1.12 so in the meantime, i have to use CS for player shops. Thank you for keeping me updated!
