### ISSUE TITLE
Shift click to sell/buy multiple items even if the shop is only selling 1 per click

### ISSUE THREAD

**Issue by BigMackTV** [snowgears/shopbugs#277] opened 2021-12-14 13:43 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem, just a feature that I think could be implemented. Instead of having to make multiple different shops for selling different amounts of the same item, maybe add a feature where you can shift + click to sell what you currently have in your inventory, despite the selling/buying amount (similar to chest-shops plugin feature that allows this).

The buying/selling amount would still work as normal on a right click. However, I think the shift + click feature would add an extra level of ease for players and server owners alike. 

**Describe alternatives you've considered**

I've looked through the configs and haven't found this feature yet, so either it's not there, or I'm silly and can't read properly.
I could also just make multiple different shops for selling different amounts. However, I feel like that would confuse new players more than it has to.

Especially when it comes to creating admin shops for selling/buying from.

I look forward to hearing your response.

Kind regards,

BigMackTV

**Comment by snowgears** [comment] 2021-12-14 16:48
duplicate of #159 
I am looking into this!

**Closed by snowgears** 2021-12-14 16:48 UTC
Labels: enhancement
