### ISSUE TITLE
Add GUI shop creation method

### ISSUE THREAD

**Issue by byNixo** [snowgears/shopbugs#337] opened 2022-08-13 16:25 UTC
**Is your feature request related to a problem? Please describe.**
No, actually not. It is an improvement.

**Describe the solution you'd like**
It would be a complete change from the system, but a lot better.
This is how I imagine it:
- To create a shop, the first line is to write [shop] on a sign.
  -> then a GUI opens (see pictures) where you can manage the creation of a shop.

- Right-clicking on a shop sign opens a GUI (see picture) to buy the items

**Describe alternatives you've considered**
There is already a kind of system on another server

**Additional context**
Main GUI (Set price, choose shop art):
![grafik](https://user-images.githubusercontent.com/74796414/184502059-e8f62610-3fcd-4893-b6b1-9b0de03a7142.png)
![grafik](https://user-images.githubusercontent.com/74796414/184502068-0d24dcc2-719a-4f4e-8e62-67168c06d7d8.png)
![grafik](https://user-images.githubusercontent.com/74796414/184502075-23610e61-aacc-4323-acea-1106f3bf4347.png)
![grafik](https://user-images.githubusercontent.com/74796414/184502082-608977a4-30f1-4ce6-acea-bab05a2ce845.png)
![grafik](https://user-images.githubusercontent.com/74796414/184502086-e1ddfdcf-37f8-4702-abf2-1c1eaa4ba02e.png)

select Item GUI (Select item to buy/sell):
![grafik](https://user-images.githubusercontent.com/74796414/184502113-88aa57fb-96e8-42a9-baab-53802c0156ae.png)
![grafik](https://user-images.githubusercontent.com/74796414/184502159-a7a4d825-d3fb-48db-a024-bfbf6a4983b7.png)
![grafik](https://user-images.githubusercontent.com/74796414/184502163-0cb73b4f-d54e-4ed8-95f8-e18fb7496584.png)

GUI when opening the ChestShop:
![grafik](https://user-images.githubusercontent.com/74796414/184502337-978ef168-b266-42f1-98fb-0d2ab9b440ff.png)

Shop sign:
![grafik](https://user-images.githubusercontent.com/74796414/184502349-2921629c-513d-435c-bf4e-144edd02b426.png)

What are the advantages?
- Players can create their shop more easily
- In the GUI you can see the items exactly. means the enchantments etc.
- It's easier to buy the items

What are the disadvantages?
- The development of the plugin

**Comment by snowgears** [comment] 2022-08-17 21:03
Duplicate of #288

**Closed by snowgears** 2022-08-17 21:03 UTC
Labels: enhancement, gui
