### ISSUE TITLE
gamble shops can be created by non admins

### ISSUE THREAD

**Issue by James125521** [snowgears/shopbugs#218] opened 2021-05-25 09:34 UTC
Shop - a simple, intuitive shop plugin 1.8.2.5

please change this competition shop so that it is not for players only for admin 

for 1.16.5

**Comment by snowgears** [comment] 2021-05-25 15:57
Are you referring to gamble shops? If so, this is not a bug. It is there to prevent players from duping other players.

**Comment by James125521** [comment] 2021-05-25 20:27
but I think because everyone can do it for 0 $

**Comment by James125521** [comment] 2021-05-25 20:27
without surgery

**Comment by James125521** [comment] 2021-05-25 20:28
And then what do I need the shop for if I can just take gambling deals for $ 0

**Comment by snowgears** [comment] 2021-06-08 19:38
Fixed in 1.8.2.6 (in progress)

**Closed by snowgears** 2021-06-08 19:38 UTC
Labels: bug
