### ISSUE TITLE
Offline players do not receive money

### ISSUE THREAD

**Issue by Paazu** [snowgears/shopbugs#214] opened 2021-05-14 17:10 UTC
A player (admin) went offline, I bought him an iron block, and he never got the money ($ 150)

To reproduce, 
- Build a shop
- Disconnect
- wait a player buy a item
- Reconnect on the server.
- See your money, you don't have anything

The player was supposed to receive the money he won through the shop, even offline. Unless this feature does not exist yet?

https://imgur.com/a/XX2s8oe

Purpur version git-Purpur-1085 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

 - Shop version: 1.8.2.4

My best greetings,
Paaz_

**Comment by snowgears** [comment] 2021-05-19 00:52
What economy plugin are you using? This is most likely a problem with that

**Comment by snowgears** [comment] 2021-05-21 20:10
Closing until question about economy plugin is answered. Cannot reproduce

**Closed by snowgears** 2021-05-21 20:10 UTC
Labels: bug, question
