### ISSUE TITLE
EnderChestHandler - save inventory error

### ISSUE THREAD

**Issue by Wastinqs** [snowgears/shopbugs#364] opened 2022-12-01 19:57 UTC
https://justpaste.it/d3auk

Can't get it fixed

Also newest version I can't run because if players use stacked crates in inventory and use right-click they get disconnected because of sending too many packets.

**Comment by snowgears** [comment] 2022-12-15 18:02
Somehow an itemstack is being added to an enderchest that is not serializable. This is most likely caused by another plugin improperly adding a null enchantment. Going forward, shop will strip out any items that are not serializable when it saves enderchests to prevent this error going forward.

Fixed in 1.8.4.1 (in progress)

**Comment by snowgears** [comment] 2023-01-23 23:50
Fixed in 1.8.4.2 (in progress)

I am no longer saving ender chest inventories to a file and have switched to a new system where I load player DAT files and interact directly with NBT for offline enderchests.

**Closed by snowgears** 2023-01-23 23:50 UTC
Labels: bug
